### ISSUE TITLE
TAC-LS Patch conflict

### ISSUE THREAD

**Issue by deadpoets** [linuxgurugamer/K2_Command_Pod#6]
The patch for Tac-LS included in K2_Command_Pod { JFJohnny5\MM_Patches\MM_TACLifeSupport.cfg } seems to conflict with the one included in Tac-LS { [ThunderAerospace\TacLifeSupport\MM_StockPartChanges.cfg](https://github.com/KSP-RO/TacLifeSupport/blob/master/GameData/ThunderAerospace/TacLifeSupport/MM_StockPartChanges.cfg) } producing an error during ModuleManager patching specifically the k2pod-1875. 

I do not believe you require a Tac-LS patch for your pods any longer, as the Tac-LS patch modifies any part with crew capacity now.

**Comment by linuxgurugamer** [comment]
Thank you, will get to this soon
